apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "goose-k8s-demo.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "goose-k8s-demo.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.goose.config | nindent 4 }}
