{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "goose-k8s-demo.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "goose-k8s-demo.fullname" . }}-cluster-role
  labels:
    {{- include "goose-k8s-demo.labels" . | nindent 4 }}
rules:
{{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "goose-k8s-demo.fullname" . }}-cluster-role-binding
  labels:
    {{- include "goose-k8s-demo.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "goose-k8s-demo.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
