{{- if .Values.ingress.enabled -}}
{{- $fullName := include "k8s-chat.fullname" . -}}
{{- $frontendSvcPort := .Values.service.frontend.port -}}
{{- if and .Values.ingress.className (not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class")) }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "k8s-chat.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                {{- if eq $.Values.deploymentMode "single" }}
                name: {{ $fullName }}
                {{- else }}
                name: {{ $fullName }}-frontend
                {{- end }}
                port:
                  number: {{ $frontendSvcPort }}
              {{- else }}
              {{- if eq $.Values.deploymentMode "single" }}
              serviceName: {{ $fullName }}
              {{- else }}
              serviceName: {{ $fullName }}-frontend
              {{- end }}
              servicePort: {{ $frontendSvcPort }}
              {{- end }}
          {{- end }}
          - path: /api
            {{- if and (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                {{- if eq $.Values.deploymentMode "single" }}
                name: {{ $fullName }}
                port:
                  number: {{ $frontendSvcPort }}
                {{- else }}
                name: {{ $fullName }}-backend
                port:
                  number: {{ $.Values.service.backend.port }}
                {{- end }}
              {{- else }}
              {{- if eq $.Values.deploymentMode "single" }}
              serviceName: {{ $fullName }}
              servicePort: {{ $frontendSvcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-backend
              servicePort: {{ $.Values.service.backend.port }}
              {{- end }}
              {{- end }}
    {{- end }}
{{- end }}
